// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: deltamem.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeltaMem_Store_FullMethodName             = "/deltamem.DeltaMem/Store"
	DeltaMem_Recall_FullMethodName            = "/deltamem.DeltaMem/Recall"
	DeltaMem_StoreHidden_FullMethodName       = "/deltamem.DeltaMem/StoreHidden"
	DeltaMem_RecallHidden_FullMethodName      = "/deltamem.DeltaMem/RecallHidden"
	DeltaMem_Health_FullMethodName            = "/deltamem.DeltaMem/Health"
	DeltaMem_ResetState_FullMethodName        = "/deltamem.DeltaMem/ResetState"
	DeltaMem_IBNNForward_FullMethodName       = "/deltamem.DeltaMem/IBNNForward"
	DeltaMem_IBNNForwardHidden_FullMethodName = "/deltamem.DeltaMem/IBNNForwardHidden"
	DeltaMem_TurboAdd_FullMethodName          = "/deltamem.DeltaMem/TurboAdd"
	DeltaMem_TurboSearch_FullMethodName       = "/deltamem.DeltaMem/TurboSearch"
	DeltaMem_Generate_FullMethodName          = "/deltamem.DeltaMem/Generate"
	DeltaMem_Think_FullMethodName             = "/deltamem.DeltaMem/Think"
	DeltaMem_StartWander_FullMethodName       = "/deltamem.DeltaMem/StartWander"
	DeltaMem_StopWander_FullMethodName        = "/deltamem.DeltaMem/StopWander"
	DeltaMem_HarvestWander_FullMethodName     = "/deltamem.DeltaMem/HarvestWander"
	DeltaMem_AddAxiom_FullMethodName          = "/deltamem.DeltaMem/AddAxiom"
	DeltaMem_Adapt_FullMethodName             = "/deltamem.DeltaMem/Adapt"
	DeltaMem_Learn_FullMethodName             = "/deltamem.DeltaMem/Learn"
	DeltaMem_Forget_FullMethodName            = "/deltamem.DeltaMem/Forget"
	DeltaMem_StoreDeep_FullMethodName         = "/deltamem.DeltaMem/StoreDeep"
	DeltaMem_TurbogoSearch_FullMethodName     = "/deltamem.DeltaMem/TurbogoSearch"
	DeltaMem_SessionSearch_FullMethodName     = "/deltamem.DeltaMem/SessionSearch"
	DeltaMem_Validate_FullMethodName          = "/deltamem.DeltaMem/Validate"
	DeltaMem_QueryTemporal_FullMethodName     = "/deltamem.DeltaMem/QueryTemporal"
	DeltaMem_AmIConfident_FullMethodName      = "/deltamem.DeltaMem/AmIConfident"
)

// DeltaMemClient is the client API for DeltaMem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeltaMemClient interface {
	// Original δ-mem methods (kept for backward compatibility)
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
	StoreHidden(ctx context.Context, in *HiddenStoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	RecallHidden(ctx context.Context, in *HiddenRecallRequest, opts ...grpc.CallOption) (*HiddenRecallResponse, error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	ResetState(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error)
	// New methods — fully exposed (nomic + IBNN + turbovec + Gemma 4 QAT)
	IBNNForward(ctx context.Context, in *IBNNForwardRequest, opts ...grpc.CallOption) (*IBNNForwardResponse, error)
	IBNNForwardHidden(ctx context.Context, in *IBNNForwardHiddenRequest, opts ...grpc.CallOption) (*IBNNForwardResponse, error)
	TurboAdd(ctx context.Context, in *TurboAddRequest, opts ...grpc.CallOption) (*TurboAddResponse, error)
	TurboSearch(ctx context.Context, in *TurboSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error)
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	// Thoughts — novel idea synthesis
	Think(ctx context.Context, in *ThinkRequest, opts ...grpc.CallOption) (*ThinkResponse, error)
	StartWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error)
	StopWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error)
	HarvestWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*HarvestResponse, error)
	AddAxiom(ctx context.Context, in *AxiomRequest, opts ...grpc.CallOption) (*Empty, error)
	Adapt(ctx context.Context, in *AdaptRequest, opts ...grpc.CallOption) (*AdaptResponse, error)
	Learn(ctx context.Context, in *LearnRequest, opts ...grpc.CallOption) (*Empty, error)
	Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*Empty, error)
	// Full-pipeline RPCs — all layers wired
	StoreDeep(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreDeepResponse, error)
	TurbogoSearch(ctx context.Context, in *TurboSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error)
	SessionSearch(ctx context.Context, in *SessionSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	QueryTemporal(ctx context.Context, in *TemporalRequest, opts ...grpc.CallOption) (*TemporalResponse, error)
	AmIConfident(ctx context.Context, in *ConfidenceRequest, opts ...grpc.CallOption) (*ConfidenceResponse, error)
}

type deltaMemClient struct {
	cc grpc.ClientConnInterface
}

func NewDeltaMemClient(cc grpc.ClientConnInterface) DeltaMemClient {
	return &deltaMemClient{cc}
}

func (c *deltaMemClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) StoreHidden(ctx context.Context, in *HiddenStoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, DeltaMem_StoreHidden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) RecallHidden(ctx context.Context, in *HiddenRecallRequest, opts ...grpc.CallOption) (*HiddenRecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HiddenRecallResponse)
	err := c.cc.Invoke(ctx, DeltaMem_RecallHidden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) ResetState(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_ResetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) IBNNForward(ctx context.Context, in *IBNNForwardRequest, opts ...grpc.CallOption) (*IBNNForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IBNNForwardResponse)
	err := c.cc.Invoke(ctx, DeltaMem_IBNNForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) IBNNForwardHidden(ctx context.Context, in *IBNNForwardHiddenRequest, opts ...grpc.CallOption) (*IBNNForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IBNNForwardResponse)
	err := c.cc.Invoke(ctx, DeltaMem_IBNNForwardHidden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) TurboAdd(ctx context.Context, in *TurboAddRequest, opts ...grpc.CallOption) (*TurboAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurboAddResponse)
	err := c.cc.Invoke(ctx, DeltaMem_TurboAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) TurboSearch(ctx context.Context, in *TurboSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurboSearchResponse)
	err := c.cc.Invoke(ctx, DeltaMem_TurboSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Think(ctx context.Context, in *ThinkRequest, opts ...grpc.CallOption) (*ThinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThinkResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Think_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) StartWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_StartWander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) StopWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_StopWander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) HarvestWander(ctx context.Context, in *OwnerRequest, opts ...grpc.CallOption) (*HarvestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HarvestResponse)
	err := c.cc.Invoke(ctx, DeltaMem_HarvestWander_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) AddAxiom(ctx context.Context, in *AxiomRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_AddAxiom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Adapt(ctx context.Context, in *AdaptRequest, opts ...grpc.CallOption) (*AdaptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdaptResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Adapt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Learn(ctx context.Context, in *LearnRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_Learn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeltaMem_Forget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) StoreDeep(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreDeepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreDeepResponse)
	err := c.cc.Invoke(ctx, DeltaMem_StoreDeep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) TurbogoSearch(ctx context.Context, in *TurboSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurboSearchResponse)
	err := c.cc.Invoke(ctx, DeltaMem_TurbogoSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) SessionSearch(ctx context.Context, in *SessionSearchRequest, opts ...grpc.CallOption) (*TurboSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TurboSearchResponse)
	err := c.cc.Invoke(ctx, DeltaMem_SessionSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, DeltaMem_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) QueryTemporal(ctx context.Context, in *TemporalRequest, opts ...grpc.CallOption) (*TemporalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemporalResponse)
	err := c.cc.Invoke(ctx, DeltaMem_QueryTemporal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deltaMemClient) AmIConfident(ctx context.Context, in *ConfidenceRequest, opts ...grpc.CallOption) (*ConfidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfidenceResponse)
	err := c.cc.Invoke(ctx, DeltaMem_AmIConfident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeltaMemServer is the server API for DeltaMem service.
// All implementations must embed UnimplementedDeltaMemServer
// for forward compatibility.
type DeltaMemServer interface {
	// Original δ-mem methods (kept for backward compatibility)
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	StoreHidden(context.Context, *HiddenStoreRequest) (*StoreResponse, error)
	RecallHidden(context.Context, *HiddenRecallRequest) (*HiddenRecallResponse, error)
	Health(context.Context, *Empty) (*HealthResponse, error)
	ResetState(context.Context, *OwnerRequest) (*Empty, error)
	// New methods — fully exposed (nomic + IBNN + turbovec + Gemma 4 QAT)
	IBNNForward(context.Context, *IBNNForwardRequest) (*IBNNForwardResponse, error)
	IBNNForwardHidden(context.Context, *IBNNForwardHiddenRequest) (*IBNNForwardResponse, error)
	TurboAdd(context.Context, *TurboAddRequest) (*TurboAddResponse, error)
	TurboSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error)
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	// Thoughts — novel idea synthesis
	Think(context.Context, *ThinkRequest) (*ThinkResponse, error)
	StartWander(context.Context, *OwnerRequest) (*Empty, error)
	StopWander(context.Context, *OwnerRequest) (*Empty, error)
	HarvestWander(context.Context, *OwnerRequest) (*HarvestResponse, error)
	AddAxiom(context.Context, *AxiomRequest) (*Empty, error)
	Adapt(context.Context, *AdaptRequest) (*AdaptResponse, error)
	Learn(context.Context, *LearnRequest) (*Empty, error)
	Forget(context.Context, *ForgetRequest) (*Empty, error)
	// Full-pipeline RPCs — all layers wired
	StoreDeep(context.Context, *StoreRequest) (*StoreDeepResponse, error)
	TurbogoSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error)
	SessionSearch(context.Context, *SessionSearchRequest) (*TurboSearchResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	QueryTemporal(context.Context, *TemporalRequest) (*TemporalResponse, error)
	AmIConfident(context.Context, *ConfidenceRequest) (*ConfidenceResponse, error)
	mustEmbedUnimplementedDeltaMemServer()
}

// UnimplementedDeltaMemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeltaMemServer struct{}

func (UnimplementedDeltaMemServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedDeltaMemServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedDeltaMemServer) StoreHidden(context.Context, *HiddenStoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreHidden not implemented")
}
func (UnimplementedDeltaMemServer) RecallHidden(context.Context, *HiddenRecallRequest) (*HiddenRecallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecallHidden not implemented")
}
func (UnimplementedDeltaMemServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDeltaMemServer) ResetState(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetState not implemented")
}
func (UnimplementedDeltaMemServer) IBNNForward(context.Context, *IBNNForwardRequest) (*IBNNForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IBNNForward not implemented")
}
func (UnimplementedDeltaMemServer) IBNNForwardHidden(context.Context, *IBNNForwardHiddenRequest) (*IBNNForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IBNNForwardHidden not implemented")
}
func (UnimplementedDeltaMemServer) TurboAdd(context.Context, *TurboAddRequest) (*TurboAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TurboAdd not implemented")
}
func (UnimplementedDeltaMemServer) TurboSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TurboSearch not implemented")
}
func (UnimplementedDeltaMemServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedDeltaMemServer) Think(context.Context, *ThinkRequest) (*ThinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Think not implemented")
}
func (UnimplementedDeltaMemServer) StartWander(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWander not implemented")
}
func (UnimplementedDeltaMemServer) StopWander(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWander not implemented")
}
func (UnimplementedDeltaMemServer) HarvestWander(context.Context, *OwnerRequest) (*HarvestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HarvestWander not implemented")
}
func (UnimplementedDeltaMemServer) AddAxiom(context.Context, *AxiomRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAxiom not implemented")
}
func (UnimplementedDeltaMemServer) Adapt(context.Context, *AdaptRequest) (*AdaptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Adapt not implemented")
}
func (UnimplementedDeltaMemServer) Learn(context.Context, *LearnRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Learn not implemented")
}
func (UnimplementedDeltaMemServer) Forget(context.Context, *ForgetRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Forget not implemented")
}
func (UnimplementedDeltaMemServer) StoreDeep(context.Context, *StoreRequest) (*StoreDeepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreDeep not implemented")
}
func (UnimplementedDeltaMemServer) TurbogoSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TurbogoSearch not implemented")
}
func (UnimplementedDeltaMemServer) SessionSearch(context.Context, *SessionSearchRequest) (*TurboSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionSearch not implemented")
}
func (UnimplementedDeltaMemServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedDeltaMemServer) QueryTemporal(context.Context, *TemporalRequest) (*TemporalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTemporal not implemented")
}
func (UnimplementedDeltaMemServer) AmIConfident(context.Context, *ConfidenceRequest) (*ConfidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AmIConfident not implemented")
}
func (UnimplementedDeltaMemServer) mustEmbedUnimplementedDeltaMemServer() {}
func (UnimplementedDeltaMemServer) testEmbeddedByValue()                  {}

// UnsafeDeltaMemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeltaMemServer will
// result in compilation errors.
type UnsafeDeltaMemServer interface {
	mustEmbedUnimplementedDeltaMemServer()
}

func RegisterDeltaMemServer(s grpc.ServiceRegistrar, srv DeltaMemServer) {
	// If the following call panics, it indicates UnimplementedDeltaMemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeltaMem_ServiceDesc, srv)
}

func _DeltaMem_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_StoreHidden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiddenStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).StoreHidden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_StoreHidden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).StoreHidden(ctx, req.(*HiddenStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_RecallHidden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HiddenRecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).RecallHidden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_RecallHidden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).RecallHidden(ctx, req.(*HiddenRecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_ResetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).ResetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_ResetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).ResetState(ctx, req.(*OwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_IBNNForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IBNNForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).IBNNForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_IBNNForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).IBNNForward(ctx, req.(*IBNNForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_IBNNForwardHidden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IBNNForwardHiddenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).IBNNForwardHidden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_IBNNForwardHidden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).IBNNForwardHidden(ctx, req.(*IBNNForwardHiddenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_TurboAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurboAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).TurboAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_TurboAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).TurboAdd(ctx, req.(*TurboAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_TurboSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurboSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).TurboSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_TurboSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).TurboSearch(ctx, req.(*TurboSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Think_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Think(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Think_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Think(ctx, req.(*ThinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_StartWander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).StartWander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_StartWander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).StartWander(ctx, req.(*OwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_StopWander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).StopWander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_StopWander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).StopWander(ctx, req.(*OwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_HarvestWander_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).HarvestWander(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_HarvestWander_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).HarvestWander(ctx, req.(*OwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_AddAxiom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AxiomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).AddAxiom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_AddAxiom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).AddAxiom(ctx, req.(*AxiomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Adapt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdaptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Adapt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Adapt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Adapt(ctx, req.(*AdaptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Learn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Learn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Learn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Learn(ctx, req.(*LearnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Forget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Forget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Forget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Forget(ctx, req.(*ForgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_StoreDeep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).StoreDeep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_StoreDeep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).StoreDeep(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_TurbogoSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TurboSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).TurbogoSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_TurbogoSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).TurbogoSearch(ctx, req.(*TurboSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_SessionSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).SessionSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_SessionSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).SessionSearch(ctx, req.(*SessionSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_QueryTemporal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemporalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).QueryTemporal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_QueryTemporal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).QueryTemporal(ctx, req.(*TemporalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeltaMem_AmIConfident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeltaMemServer).AmIConfident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeltaMem_AmIConfident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeltaMemServer).AmIConfident(ctx, req.(*ConfidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeltaMem_ServiceDesc is the grpc.ServiceDesc for DeltaMem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeltaMem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deltamem.DeltaMem",
	HandlerType: (*DeltaMemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _DeltaMem_Store_Handler,
		},
		{
			MethodName: "Recall",
			Handler:    _DeltaMem_Recall_Handler,
		},
		{
			MethodName: "StoreHidden",
			Handler:    _DeltaMem_StoreHidden_Handler,
		},
		{
			MethodName: "RecallHidden",
			Handler:    _DeltaMem_RecallHidden_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DeltaMem_Health_Handler,
		},
		{
			MethodName: "ResetState",
			Handler:    _DeltaMem_ResetState_Handler,
		},
		{
			MethodName: "IBNNForward",
			Handler:    _DeltaMem_IBNNForward_Handler,
		},
		{
			MethodName: "IBNNForwardHidden",
			Handler:    _DeltaMem_IBNNForwardHidden_Handler,
		},
		{
			MethodName: "TurboAdd",
			Handler:    _DeltaMem_TurboAdd_Handler,
		},
		{
			MethodName: "TurboSearch",
			Handler:    _DeltaMem_TurboSearch_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _DeltaMem_Generate_Handler,
		},
		{
			MethodName: "Think",
			Handler:    _DeltaMem_Think_Handler,
		},
		{
			MethodName: "StartWander",
			Handler:    _DeltaMem_StartWander_Handler,
		},
		{
			MethodName: "StopWander",
			Handler:    _DeltaMem_StopWander_Handler,
		},
		{
			MethodName: "HarvestWander",
			Handler:    _DeltaMem_HarvestWander_Handler,
		},
		{
			MethodName: "AddAxiom",
			Handler:    _DeltaMem_AddAxiom_Handler,
		},
		{
			MethodName: "Adapt",
			Handler:    _DeltaMem_Adapt_Handler,
		},
		{
			MethodName: "Learn",
			Handler:    _DeltaMem_Learn_Handler,
		},
		{
			MethodName: "Forget",
			Handler:    _DeltaMem_Forget_Handler,
		},
		{
			MethodName: "StoreDeep",
			Handler:    _DeltaMem_StoreDeep_Handler,
		},
		{
			MethodName: "TurbogoSearch",
			Handler:    _DeltaMem_TurbogoSearch_Handler,
		},
		{
			MethodName: "SessionSearch",
			Handler:    _DeltaMem_SessionSearch_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _DeltaMem_Validate_Handler,
		},
		{
			MethodName: "QueryTemporal",
			Handler:    _DeltaMem_QueryTemporal_Handler,
		},
		{
			MethodName: "AmIConfident",
			Handler:    _DeltaMem_AmIConfident_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deltamem.proto",
}
