// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: deltamem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Original messages (unchanged)
type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_deltamem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	StateNorm     float32                `protobuf:"fixed32,2,opt,name=state_norm,json=stateNorm,proto3" json:"state_norm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_deltamem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreResponse) GetStateNorm() float32 {
	if x != nil {
		return x.StateNorm
	}
	return 0
}

type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_deltamem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{2}
}

func (x *RecallRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correction    []float32              `protobuf:"fixed32,1,rep,packed,name=correction,proto3" json:"correction,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_deltamem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{3}
}

func (x *RecallResponse) GetCorrection() []float32 {
	if x != nil {
		return x.Correction
	}
	return nil
}

func (x *RecallResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type HiddenStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HiddenState   []float32              `protobuf:"fixed32,2,rep,packed,name=hidden_state,json=hiddenState,proto3" json:"hidden_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenStoreRequest) Reset() {
	*x = HiddenStoreRequest{}
	mi := &file_deltamem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenStoreRequest) ProtoMessage() {}

func (x *HiddenStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenStoreRequest.ProtoReflect.Descriptor instead.
func (*HiddenStoreRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{4}
}

func (x *HiddenStoreRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HiddenStoreRequest) GetHiddenState() []float32 {
	if x != nil {
		return x.HiddenState
	}
	return nil
}

type HiddenRecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	QueryState    []float32              `protobuf:"fixed32,2,rep,packed,name=query_state,json=queryState,proto3" json:"query_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenRecallRequest) Reset() {
	*x = HiddenRecallRequest{}
	mi := &file_deltamem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenRecallRequest) ProtoMessage() {}

func (x *HiddenRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenRecallRequest.ProtoReflect.Descriptor instead.
func (*HiddenRecallRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{5}
}

func (x *HiddenRecallRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HiddenRecallRequest) GetQueryState() []float32 {
	if x != nil {
		return x.QueryState
	}
	return nil
}

type HiddenRecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaQ        []float32              `protobuf:"fixed32,1,rep,packed,name=delta_q,json=deltaQ,proto3" json:"delta_q,omitempty"`
	DeltaO        []float32              `protobuf:"fixed32,2,rep,packed,name=delta_o,json=deltaO,proto3" json:"delta_o,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenRecallResponse) Reset() {
	*x = HiddenRecallResponse{}
	mi := &file_deltamem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenRecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenRecallResponse) ProtoMessage() {}

func (x *HiddenRecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenRecallResponse.ProtoReflect.Descriptor instead.
func (*HiddenRecallResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{6}
}

func (x *HiddenRecallResponse) GetDeltaQ() []float32 {
	if x != nil {
		return x.DeltaQ
	}
	return nil
}

func (x *HiddenRecallResponse) GetDeltaO() []float32 {
	if x != nil {
		return x.DeltaO
	}
	return nil
}

func (x *HiddenRecallResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnersActive  int32                  `protobuf:"varint,1,opt,name=owners_active,json=ownersActive,proto3" json:"owners_active,omitempty"`
	AvgStateNorm  float32                `protobuf:"fixed32,2,opt,name=avg_state_norm,json=avgStateNorm,proto3" json:"avg_state_norm,omitempty"`
	TotalStores   int64                  `protobuf:"varint,3,opt,name=total_stores,json=totalStores,proto3" json:"total_stores,omitempty"`
	TotalRecalls  int64                  `protobuf:"varint,4,opt,name=total_recalls,json=totalRecalls,proto3" json:"total_recalls,omitempty"`
	Uptime        string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_deltamem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetOwnersActive() int32 {
	if x != nil {
		return x.OwnersActive
	}
	return 0
}

func (x *HealthResponse) GetAvgStateNorm() float32 {
	if x != nil {
		return x.AvgStateNorm
	}
	return 0
}

func (x *HealthResponse) GetTotalStores() int64 {
	if x != nil {
		return x.TotalStores
	}
	return 0
}

func (x *HealthResponse) GetTotalRecalls() int64 {
	if x != nil {
		return x.TotalRecalls
	}
	return 0
}

func (x *HealthResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type OwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnerRequest) Reset() {
	*x = OwnerRequest{}
	mi := &file_deltamem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerRequest) ProtoMessage() {}

func (x *OwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerRequest.ProtoReflect.Descriptor instead.
func (*OwnerRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{8}
}

func (x *OwnerRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_deltamem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{9}
}

// New messages for IBNN, turbovec, Gemma 4 QAT
type IBNNForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IBNNForwardRequest) Reset() {
	*x = IBNNForwardRequest{}
	mi := &file_deltamem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBNNForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBNNForwardRequest) ProtoMessage() {}

func (x *IBNNForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBNNForwardRequest.ProtoReflect.Descriptor instead.
func (*IBNNForwardRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{10}
}

func (x *IBNNForwardRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *IBNNForwardRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IBNNForwardHiddenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	HiddenState   []float32              `protobuf:"fixed32,2,rep,packed,name=hidden_state,json=hiddenState,proto3" json:"hidden_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IBNNForwardHiddenRequest) Reset() {
	*x = IBNNForwardHiddenRequest{}
	mi := &file_deltamem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBNNForwardHiddenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBNNForwardHiddenRequest) ProtoMessage() {}

func (x *IBNNForwardHiddenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBNNForwardHiddenRequest.ProtoReflect.Descriptor instead.
func (*IBNNForwardHiddenRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{11}
}

func (x *IBNNForwardHiddenRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *IBNNForwardHiddenRequest) GetHiddenState() []float32 {
	if x != nil {
		return x.HiddenState
	}
	return nil
}

type IBNNForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []float32              `protobuf:"fixed32,1,rep,packed,name=output,proto3" json:"output,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IBNNForwardResponse) Reset() {
	*x = IBNNForwardResponse{}
	mi := &file_deltamem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IBNNForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IBNNForwardResponse) ProtoMessage() {}

func (x *IBNNForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IBNNForwardResponse.ProtoReflect.Descriptor instead.
func (*IBNNForwardResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{12}
}

func (x *IBNNForwardResponse) GetOutput() []float32 {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *IBNNForwardResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

type TurboAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurboAddRequest) Reset() {
	*x = TurboAddRequest{}
	mi := &file_deltamem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboAddRequest) ProtoMessage() {}

func (x *TurboAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboAddRequest.ProtoReflect.Descriptor instead.
func (*TurboAddRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{13}
}

func (x *TurboAddRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TurboAddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TurboAddRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type TurboAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurboAddResponse) Reset() {
	*x = TurboAddResponse{}
	mi := &file_deltamem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboAddResponse) ProtoMessage() {}

func (x *TurboAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboAddResponse.ProtoReflect.Descriptor instead.
func (*TurboAddResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{14}
}

func (x *TurboAddResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TurboSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Query         []float32              `protobuf:"fixed32,2,rep,packed,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurboSearchRequest) Reset() {
	*x = TurboSearchRequest{}
	mi := &file_deltamem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboSearchRequest) ProtoMessage() {}

func (x *TurboSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboSearchRequest.ProtoReflect.Descriptor instead.
func (*TurboSearchRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{15}
}

func (x *TurboSearchRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TurboSearchRequest) GetQuery() []float32 {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *TurboSearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type TurboSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Scores        []float32              `protobuf:"fixed32,2,rep,packed,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurboSearchResponse) Reset() {
	*x = TurboSearchResponse{}
	mi := &file_deltamem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboSearchResponse) ProtoMessage() {}

func (x *TurboSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboSearchResponse.ProtoReflect.Descriptor instead.
func (*TurboSearchResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{16}
}

func (x *TurboSearchResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *TurboSearchResponse) GetScores() []float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_deltamem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_deltamem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ThinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Seeds         []string               `protobuf:"bytes,2,rep,name=seeds,proto3" json:"seeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkRequest) Reset() {
	*x = ThinkRequest{}
	mi := &file_deltamem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkRequest) ProtoMessage() {}

func (x *ThinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkRequest.ProtoReflect.Descriptor instead.
func (*ThinkRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{19}
}

func (x *ThinkRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ThinkRequest) GetSeeds() []string {
	if x != nil {
		return x.Seeds
	}
	return nil
}

type ThinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idea          string                 `protobuf:"bytes,1,opt,name=idea,proto3" json:"idea,omitempty"`
	Seeds         []string               `protobuf:"bytes,2,rep,name=seeds,proto3" json:"seeds,omitempty"`
	Neighbors     []string               `protobuf:"bytes,3,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Novelty       float32                `protobuf:"fixed32,5,opt,name=novelty,proto3" json:"novelty,omitempty"`
	Grounding     float32                `protobuf:"fixed32,6,opt,name=grounding,proto3" json:"grounding,omitempty"`
	Depth         int32                  `protobuf:"varint,7,opt,name=depth,proto3" json:"depth,omitempty"`
	Valid         bool                   `protobuf:"varint,8,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkResponse) Reset() {
	*x = ThinkResponse{}
	mi := &file_deltamem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkResponse) ProtoMessage() {}

func (x *ThinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkResponse.ProtoReflect.Descriptor instead.
func (*ThinkResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{20}
}

func (x *ThinkResponse) GetIdea() string {
	if x != nil {
		return x.Idea
	}
	return ""
}

func (x *ThinkResponse) GetSeeds() []string {
	if x != nil {
		return x.Seeds
	}
	return nil
}

func (x *ThinkResponse) GetNeighbors() []string {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *ThinkResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ThinkResponse) GetNovelty() float32 {
	if x != nil {
		return x.Novelty
	}
	return 0
}

func (x *ThinkResponse) GetGrounding() float32 {
	if x != nil {
		return x.Grounding
	}
	return 0
}

func (x *ThinkResponse) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ThinkResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type HarvestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thoughts      []*ThinkResponse       `protobuf:"bytes,1,rep,name=thoughts,proto3" json:"thoughts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarvestResponse) Reset() {
	*x = HarvestResponse{}
	mi := &file_deltamem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarvestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarvestResponse) ProtoMessage() {}

func (x *HarvestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarvestResponse.ProtoReflect.Descriptor instead.
func (*HarvestResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{21}
}

func (x *HarvestResponse) GetThoughts() []*ThinkResponse {
	if x != nil {
		return x.Thoughts
	}
	return nil
}

type AxiomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statement     string                 `protobuf:"bytes,1,opt,name=statement,proto3" json:"statement,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AxiomRequest) Reset() {
	*x = AxiomRequest{}
	mi := &file_deltamem_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AxiomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AxiomRequest) ProtoMessage() {}

func (x *AxiomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AxiomRequest.ProtoReflect.Descriptor instead.
func (*AxiomRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{22}
}

func (x *AxiomRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *AxiomRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type AdaptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Wrong         string                 `protobuf:"bytes,2,opt,name=wrong,proto3" json:"wrong,omitempty"`
	Right         string                 `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptRequest) Reset() {
	*x = AdaptRequest{}
	mi := &file_deltamem_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptRequest) ProtoMessage() {}

func (x *AdaptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptRequest.ProtoReflect.Descriptor instead.
func (*AdaptRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{23}
}

func (x *AdaptRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AdaptRequest) GetWrong() string {
	if x != nil {
		return x.Wrong
	}
	return ""
}

func (x *AdaptRequest) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

type AdaptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Impact        float32                `protobuf:"fixed32,1,opt,name=impact,proto3" json:"impact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdaptResponse) Reset() {
	*x = AdaptResponse{}
	mi := &file_deltamem_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdaptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdaptResponse) ProtoMessage() {}

func (x *AdaptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdaptResponse.ProtoReflect.Descriptor instead.
func (*AdaptResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{24}
}

func (x *AdaptResponse) GetImpact() float32 {
	if x != nil {
		return x.Impact
	}
	return 0
}

type LearnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Fact          string                 `protobuf:"bytes,2,opt,name=fact,proto3" json:"fact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearnRequest) Reset() {
	*x = LearnRequest{}
	mi := &file_deltamem_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearnRequest) ProtoMessage() {}

func (x *LearnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearnRequest.ProtoReflect.Descriptor instead.
func (*LearnRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{25}
}

func (x *LearnRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LearnRequest) GetFact() string {
	if x != nil {
		return x.Fact
	}
	return ""
}

type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	What          string                 `protobuf:"bytes,2,opt,name=what,proto3" json:"what,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_deltamem_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{26}
}

func (x *ForgetRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ForgetRequest) GetWhat() string {
	if x != nil {
		return x.What
	}
	return ""
}

// StoreDeep response — includes all layer feedback
type StoreDeepResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	StateNorm      float32                `protobuf:"fixed32,2,opt,name=state_norm,json=stateNorm,proto3" json:"state_norm,omitempty"`                // δ-mem norm after store
	IbnnReinforced float32                `protobuf:"fixed32,3,opt,name=ibnn_reinforced,json=ibnnReinforced,proto3" json:"ibnn_reinforced,omitempty"` // IBNN learning rate applied
	TurbogoId      string                 `protobuf:"bytes,4,opt,name=turbogo_id,json=turbogoId,proto3" json:"turbogo_id,omitempty"`                  // ID in turbogo index
	TurbovecId     string                 `protobuf:"bytes,5,opt,name=turbovec_id,json=turbovecId,proto3" json:"turbovec_id,omitempty"`               // ID in turbovec index
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreDeepResponse) Reset() {
	*x = StoreDeepResponse{}
	mi := &file_deltamem_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreDeepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreDeepResponse) ProtoMessage() {}

func (x *StoreDeepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreDeepResponse.ProtoReflect.Descriptor instead.
func (*StoreDeepResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{27}
}

func (x *StoreDeepResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StoreDeepResponse) GetStateNorm() float32 {
	if x != nil {
		return x.StateNorm
	}
	return 0
}

func (x *StoreDeepResponse) GetIbnnReinforced() float32 {
	if x != nil {
		return x.IbnnReinforced
	}
	return 0
}

func (x *StoreDeepResponse) GetTurbogoId() string {
	if x != nil {
		return x.TurbogoId
	}
	return ""
}

func (x *StoreDeepResponse) GetTurbovecId() string {
	if x != nil {
		return x.TurbovecId
	}
	return ""
}

// Truth validation
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Statement     string                 `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_deltamem_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{28}
}

func (x *ValidateRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ValidateRequest) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

type ValidateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Valid          bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Grounding      float32                `protobuf:"fixed32,2,opt,name=grounding,proto3" json:"grounding,omitempty"`
	Coherence      float32                `protobuf:"fixed32,3,opt,name=coherence,proto3" json:"coherence,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Contradictions []string               `protobuf:"bytes,5,rep,name=contradictions,proto3" json:"contradictions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_deltamem_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{29}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetGrounding() float32 {
	if x != nil {
		return x.Grounding
	}
	return 0
}

func (x *ValidateResponse) GetCoherence() float32 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *ValidateResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ValidateResponse) GetContradictions() []string {
	if x != nil {
		return x.Contradictions
	}
	return nil
}

// Temporal query
type TemporalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalRequest) Reset() {
	*x = TemporalRequest{}
	mi := &file_deltamem_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalRequest) ProtoMessage() {}

func (x *TemporalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalRequest.ProtoReflect.Descriptor instead.
func (*TemporalRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{30}
}

func (x *TemporalRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TemporalRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TemporalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TemporalEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalResponse) Reset() {
	*x = TemporalResponse{}
	mi := &file_deltamem_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalResponse) ProtoMessage() {}

func (x *TemporalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalResponse.ProtoReflect.Descriptor instead.
func (*TemporalResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{31}
}

func (x *TemporalResponse) GetEvents() []*TemporalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TemporalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	When          string                 `protobuf:"bytes,3,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalEvent) Reset() {
	*x = TemporalEvent{}
	mi := &file_deltamem_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalEvent) ProtoMessage() {}

func (x *TemporalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalEvent.ProtoReflect.Descriptor instead.
func (*TemporalEvent) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{32}
}

func (x *TemporalEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemporalEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TemporalEvent) GetWhen() string {
	if x != nil {
		return x.When
	}
	return ""
}

// Self-model confidence
type ConfidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfidenceRequest) Reset() {
	*x = ConfidenceRequest{}
	mi := &file_deltamem_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceRequest) ProtoMessage() {}

func (x *ConfidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceRequest.ProtoReflect.Descriptor instead.
func (*ConfidenceRequest) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{33}
}

func (x *ConfidenceRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ConfidenceRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ConfidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"` // 0=NeverSeen, 1=Low, 2=Medium, 3=High
	RawScore      float32                `protobuf:"fixed32,2,opt,name=raw_score,json=rawScore,proto3" json:"raw_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfidenceResponse) Reset() {
	*x = ConfidenceResponse{}
	mi := &file_deltamem_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceResponse) ProtoMessage() {}

func (x *ConfidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deltamem_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceResponse.ProtoReflect.Descriptor instead.
func (*ConfidenceResponse) Descriptor() ([]byte, []int) {
	return file_deltamem_proto_rawDescGZIP(), []int{34}
}

func (x *ConfidenceResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ConfidenceResponse) GetRawScore() float32 {
	if x != nil {
		return x.RawScore
	}
	return 0
}

var File_deltamem_proto protoreflect.FileDescriptor

const file_deltamem_proto_rawDesc = "" +
	"\n" +
	"\x0edeltamem.proto\x12\bdeltamem\"P\n" +
	"\fStoreRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\">\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"state_norm\x18\x02 \x01(\x02R\tstateNorm\";\n" +
	"\rRecallRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"P\n" +
	"\x0eRecallResponse\x12\x1e\n" +
	"\n" +
	"correction\x18\x01 \x03(\x02R\n" +
	"correction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\"M\n" +
	"\x12HiddenStoreRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12!\n" +
	"\fhidden_state\x18\x02 \x03(\x02R\vhiddenState\"L\n" +
	"\x13HiddenRecallRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1f\n" +
	"\vquery_state\x18\x02 \x03(\x02R\n" +
	"queryState\"h\n" +
	"\x14HiddenRecallResponse\x12\x17\n" +
	"\adelta_q\x18\x01 \x03(\x02R\x06deltaQ\x12\x17\n" +
	"\adelta_o\x18\x02 \x03(\x02R\x06deltaO\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"\xbb\x01\n" +
	"\x0eHealthResponse\x12#\n" +
	"\rowners_active\x18\x01 \x01(\x05R\fownersActive\x12$\n" +
	"\x0eavg_state_norm\x18\x02 \x01(\x02R\favgStateNorm\x12!\n" +
	"\ftotal_stores\x18\x03 \x01(\x03R\vtotalStores\x12#\n" +
	"\rtotal_recalls\x18\x04 \x01(\x03R\ftotalRecalls\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\"$\n" +
	"\fOwnerRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\"\a\n" +
	"\x05Empty\">\n" +
	"\x12IBNNForwardRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"S\n" +
	"\x18IBNNForwardHiddenRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12!\n" +
	"\fhidden_state\x18\x02 \x03(\x02R\vhiddenState\"?\n" +
	"\x13IBNNForwardResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\x02R\x06output\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\"O\n" +
	"\x0fTurboAddRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\"\"\n" +
	"\x10TurboAddResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"N\n" +
	"\x12TurboSearchRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05query\x18\x02 \x03(\x02R\x05query\x12\f\n" +
	"\x01k\x18\x03 \x01(\x05R\x01k\"?\n" +
	"\x13TurboSearchResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06scores\x18\x02 \x03(\x02R\x06scores\"?\n" +
	"\x0fGenerateRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\".\n" +
	"\x10GenerateResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\":\n" +
	"\fThinkRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05seeds\x18\x02 \x03(\tR\x05seeds\"\xdb\x01\n" +
	"\rThinkResponse\x12\x12\n" +
	"\x04idea\x18\x01 \x01(\tR\x04idea\x12\x14\n" +
	"\x05seeds\x18\x02 \x03(\tR\x05seeds\x12\x1c\n" +
	"\tneighbors\x18\x03 \x03(\tR\tneighbors\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\anovelty\x18\x05 \x01(\x02R\anovelty\x12\x1c\n" +
	"\tgrounding\x18\x06 \x01(\x02R\tgrounding\x12\x14\n" +
	"\x05depth\x18\a \x01(\x05R\x05depth\x12\x14\n" +
	"\x05valid\x18\b \x01(\bR\x05valid\"F\n" +
	"\x0fHarvestResponse\x123\n" +
	"\bthoughts\x18\x01 \x03(\v2\x17.deltamem.ThinkResponseR\bthoughts\"D\n" +
	"\fAxiomRequest\x12\x1c\n" +
	"\tstatement\x18\x01 \x01(\tR\tstatement\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\"P\n" +
	"\fAdaptRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05wrong\x18\x02 \x01(\tR\x05wrong\x12\x14\n" +
	"\x05right\x18\x03 \x01(\tR\x05right\"'\n" +
	"\rAdaptResponse\x12\x16\n" +
	"\x06impact\x18\x01 \x01(\x02R\x06impact\"8\n" +
	"\fLearnRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04fact\x18\x02 \x01(\tR\x04fact\"9\n" +
	"\rForgetRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04what\x18\x02 \x01(\tR\x04what\"\xab\x01\n" +
	"\x11StoreDeepResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"state_norm\x18\x02 \x01(\x02R\tstateNorm\x12'\n" +
	"\x0fibnn_reinforced\x18\x03 \x01(\x02R\x0eibnnReinforced\x12\x1d\n" +
	"\n" +
	"turbogo_id\x18\x04 \x01(\tR\tturbogoId\x12\x1f\n" +
	"\vturbovec_id\x18\x05 \x01(\tR\n" +
	"turbovecId\"E\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1c\n" +
	"\tstatement\x18\x02 \x01(\tR\tstatement\"\xa4\x01\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1c\n" +
	"\tgrounding\x18\x02 \x01(\x02R\tgrounding\x12\x1c\n" +
	"\tcoherence\x18\x03 \x01(\x02R\tcoherence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12&\n" +
	"\x0econtradictions\x18\x05 \x03(\tR\x0econtradictions\"=\n" +
	"\x0fTemporalRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"C\n" +
	"\x10TemporalResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.deltamem.TemporalEventR\x06events\"M\n" +
	"\rTemporalEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04when\x18\x03 \x01(\tR\x04when\"=\n" +
	"\x11ConfidenceRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"G\n" +
	"\x12ConfidenceResponse\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x1b\n" +
	"\traw_score\x18\x02 \x01(\x02R\brawScore2\xa0\f\n" +
	"\bDeltaMem\x128\n" +
	"\x05Store\x12\x16.deltamem.StoreRequest\x1a\x17.deltamem.StoreResponse\x12;\n" +
	"\x06Recall\x12\x17.deltamem.RecallRequest\x1a\x18.deltamem.RecallResponse\x12D\n" +
	"\vStoreHidden\x12\x1c.deltamem.HiddenStoreRequest\x1a\x17.deltamem.StoreResponse\x12M\n" +
	"\fRecallHidden\x12\x1d.deltamem.HiddenRecallRequest\x1a\x1e.deltamem.HiddenRecallResponse\x123\n" +
	"\x06Health\x12\x0f.deltamem.Empty\x1a\x18.deltamem.HealthResponse\x125\n" +
	"\n" +
	"ResetState\x12\x16.deltamem.OwnerRequest\x1a\x0f.deltamem.Empty\x12J\n" +
	"\vIBNNForward\x12\x1c.deltamem.IBNNForwardRequest\x1a\x1d.deltamem.IBNNForwardResponse\x12V\n" +
	"\x11IBNNForwardHidden\x12\".deltamem.IBNNForwardHiddenRequest\x1a\x1d.deltamem.IBNNForwardResponse\x12A\n" +
	"\bTurboAdd\x12\x19.deltamem.TurboAddRequest\x1a\x1a.deltamem.TurboAddResponse\x12J\n" +
	"\vTurboSearch\x12\x1c.deltamem.TurboSearchRequest\x1a\x1d.deltamem.TurboSearchResponse\x12A\n" +
	"\bGenerate\x12\x19.deltamem.GenerateRequest\x1a\x1a.deltamem.GenerateResponse\x128\n" +
	"\x05Think\x12\x16.deltamem.ThinkRequest\x1a\x17.deltamem.ThinkResponse\x126\n" +
	"\vStartWander\x12\x16.deltamem.OwnerRequest\x1a\x0f.deltamem.Empty\x125\n" +
	"\n" +
	"StopWander\x12\x16.deltamem.OwnerRequest\x1a\x0f.deltamem.Empty\x12B\n" +
	"\rHarvestWander\x12\x16.deltamem.OwnerRequest\x1a\x19.deltamem.HarvestResponse\x123\n" +
	"\bAddAxiom\x12\x16.deltamem.AxiomRequest\x1a\x0f.deltamem.Empty\x128\n" +
	"\x05Adapt\x12\x16.deltamem.AdaptRequest\x1a\x17.deltamem.AdaptResponse\x120\n" +
	"\x05Learn\x12\x16.deltamem.LearnRequest\x1a\x0f.deltamem.Empty\x122\n" +
	"\x06Forget\x12\x17.deltamem.ForgetRequest\x1a\x0f.deltamem.Empty\x12@\n" +
	"\tStoreDeep\x12\x16.deltamem.StoreRequest\x1a\x1b.deltamem.StoreDeepResponse\x12L\n" +
	"\rTurbogoSearch\x12\x1c.deltamem.TurboSearchRequest\x1a\x1d.deltamem.TurboSearchResponse\x12A\n" +
	"\bValidate\x12\x19.deltamem.ValidateRequest\x1a\x1a.deltamem.ValidateResponse\x12F\n" +
	"\rQueryTemporal\x12\x19.deltamem.TemporalRequest\x1a\x1a.deltamem.TemporalResponse\x12I\n" +
	"\fAmIConfident\x12\x1b.deltamem.ConfidenceRequest\x1a\x1c.deltamem.ConfidenceResponseB,Z*github.com/dbrushchenko/delta-mem-go/protob\x06proto3"

var (
	file_deltamem_proto_rawDescOnce sync.Once
	file_deltamem_proto_rawDescData []byte
)

func file_deltamem_proto_rawDescGZIP() []byte {
	file_deltamem_proto_rawDescOnce.Do(func() {
		file_deltamem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deltamem_proto_rawDesc), len(file_deltamem_proto_rawDesc)))
	})
	return file_deltamem_proto_rawDescData
}

var file_deltamem_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_deltamem_proto_goTypes = []any{
	(*StoreRequest)(nil),             // 0: deltamem.StoreRequest
	(*StoreResponse)(nil),            // 1: deltamem.StoreResponse
	(*RecallRequest)(nil),            // 2: deltamem.RecallRequest
	(*RecallResponse)(nil),           // 3: deltamem.RecallResponse
	(*HiddenStoreRequest)(nil),       // 4: deltamem.HiddenStoreRequest
	(*HiddenRecallRequest)(nil),      // 5: deltamem.HiddenRecallRequest
	(*HiddenRecallResponse)(nil),     // 6: deltamem.HiddenRecallResponse
	(*HealthResponse)(nil),           // 7: deltamem.HealthResponse
	(*OwnerRequest)(nil),             // 8: deltamem.OwnerRequest
	(*Empty)(nil),                    // 9: deltamem.Empty
	(*IBNNForwardRequest)(nil),       // 10: deltamem.IBNNForwardRequest
	(*IBNNForwardHiddenRequest)(nil), // 11: deltamem.IBNNForwardHiddenRequest
	(*IBNNForwardResponse)(nil),      // 12: deltamem.IBNNForwardResponse
	(*TurboAddRequest)(nil),          // 13: deltamem.TurboAddRequest
	(*TurboAddResponse)(nil),         // 14: deltamem.TurboAddResponse
	(*TurboSearchRequest)(nil),       // 15: deltamem.TurboSearchRequest
	(*TurboSearchResponse)(nil),      // 16: deltamem.TurboSearchResponse
	(*GenerateRequest)(nil),          // 17: deltamem.GenerateRequest
	(*GenerateResponse)(nil),         // 18: deltamem.GenerateResponse
	(*ThinkRequest)(nil),             // 19: deltamem.ThinkRequest
	(*ThinkResponse)(nil),            // 20: deltamem.ThinkResponse
	(*HarvestResponse)(nil),          // 21: deltamem.HarvestResponse
	(*AxiomRequest)(nil),             // 22: deltamem.AxiomRequest
	(*AdaptRequest)(nil),             // 23: deltamem.AdaptRequest
	(*AdaptResponse)(nil),            // 24: deltamem.AdaptResponse
	(*LearnRequest)(nil),             // 25: deltamem.LearnRequest
	(*ForgetRequest)(nil),            // 26: deltamem.ForgetRequest
	(*StoreDeepResponse)(nil),        // 27: deltamem.StoreDeepResponse
	(*ValidateRequest)(nil),          // 28: deltamem.ValidateRequest
	(*ValidateResponse)(nil),         // 29: deltamem.ValidateResponse
	(*TemporalRequest)(nil),          // 30: deltamem.TemporalRequest
	(*TemporalResponse)(nil),         // 31: deltamem.TemporalResponse
	(*TemporalEvent)(nil),            // 32: deltamem.TemporalEvent
	(*ConfidenceRequest)(nil),        // 33: deltamem.ConfidenceRequest
	(*ConfidenceResponse)(nil),       // 34: deltamem.ConfidenceResponse
}
var file_deltamem_proto_depIdxs = []int32{
	20, // 0: deltamem.HarvestResponse.thoughts:type_name -> deltamem.ThinkResponse
	32, // 1: deltamem.TemporalResponse.events:type_name -> deltamem.TemporalEvent
	0,  // 2: deltamem.DeltaMem.Store:input_type -> deltamem.StoreRequest
	2,  // 3: deltamem.DeltaMem.Recall:input_type -> deltamem.RecallRequest
	4,  // 4: deltamem.DeltaMem.StoreHidden:input_type -> deltamem.HiddenStoreRequest
	5,  // 5: deltamem.DeltaMem.RecallHidden:input_type -> deltamem.HiddenRecallRequest
	9,  // 6: deltamem.DeltaMem.Health:input_type -> deltamem.Empty
	8,  // 7: deltamem.DeltaMem.ResetState:input_type -> deltamem.OwnerRequest
	10, // 8: deltamem.DeltaMem.IBNNForward:input_type -> deltamem.IBNNForwardRequest
	11, // 9: deltamem.DeltaMem.IBNNForwardHidden:input_type -> deltamem.IBNNForwardHiddenRequest
	13, // 10: deltamem.DeltaMem.TurboAdd:input_type -> deltamem.TurboAddRequest
	15, // 11: deltamem.DeltaMem.TurboSearch:input_type -> deltamem.TurboSearchRequest
	17, // 12: deltamem.DeltaMem.Generate:input_type -> deltamem.GenerateRequest
	19, // 13: deltamem.DeltaMem.Think:input_type -> deltamem.ThinkRequest
	8,  // 14: deltamem.DeltaMem.StartWander:input_type -> deltamem.OwnerRequest
	8,  // 15: deltamem.DeltaMem.StopWander:input_type -> deltamem.OwnerRequest
	8,  // 16: deltamem.DeltaMem.HarvestWander:input_type -> deltamem.OwnerRequest
	22, // 17: deltamem.DeltaMem.AddAxiom:input_type -> deltamem.AxiomRequest
	23, // 18: deltamem.DeltaMem.Adapt:input_type -> deltamem.AdaptRequest
	25, // 19: deltamem.DeltaMem.Learn:input_type -> deltamem.LearnRequest
	26, // 20: deltamem.DeltaMem.Forget:input_type -> deltamem.ForgetRequest
	0,  // 21: deltamem.DeltaMem.StoreDeep:input_type -> deltamem.StoreRequest
	15, // 22: deltamem.DeltaMem.TurbogoSearch:input_type -> deltamem.TurboSearchRequest
	28, // 23: deltamem.DeltaMem.Validate:input_type -> deltamem.ValidateRequest
	30, // 24: deltamem.DeltaMem.QueryTemporal:input_type -> deltamem.TemporalRequest
	33, // 25: deltamem.DeltaMem.AmIConfident:input_type -> deltamem.ConfidenceRequest
	1,  // 26: deltamem.DeltaMem.Store:output_type -> deltamem.StoreResponse
	3,  // 27: deltamem.DeltaMem.Recall:output_type -> deltamem.RecallResponse
	1,  // 28: deltamem.DeltaMem.StoreHidden:output_type -> deltamem.StoreResponse
	6,  // 29: deltamem.DeltaMem.RecallHidden:output_type -> deltamem.HiddenRecallResponse
	7,  // 30: deltamem.DeltaMem.Health:output_type -> deltamem.HealthResponse
	9,  // 31: deltamem.DeltaMem.ResetState:output_type -> deltamem.Empty
	12, // 32: deltamem.DeltaMem.IBNNForward:output_type -> deltamem.IBNNForwardResponse
	12, // 33: deltamem.DeltaMem.IBNNForwardHidden:output_type -> deltamem.IBNNForwardResponse
	14, // 34: deltamem.DeltaMem.TurboAdd:output_type -> deltamem.TurboAddResponse
	16, // 35: deltamem.DeltaMem.TurboSearch:output_type -> deltamem.TurboSearchResponse
	18, // 36: deltamem.DeltaMem.Generate:output_type -> deltamem.GenerateResponse
	20, // 37: deltamem.DeltaMem.Think:output_type -> deltamem.ThinkResponse
	9,  // 38: deltamem.DeltaMem.StartWander:output_type -> deltamem.Empty
	9,  // 39: deltamem.DeltaMem.StopWander:output_type -> deltamem.Empty
	21, // 40: deltamem.DeltaMem.HarvestWander:output_type -> deltamem.HarvestResponse
	9,  // 41: deltamem.DeltaMem.AddAxiom:output_type -> deltamem.Empty
	24, // 42: deltamem.DeltaMem.Adapt:output_type -> deltamem.AdaptResponse
	9,  // 43: deltamem.DeltaMem.Learn:output_type -> deltamem.Empty
	9,  // 44: deltamem.DeltaMem.Forget:output_type -> deltamem.Empty
	27, // 45: deltamem.DeltaMem.StoreDeep:output_type -> deltamem.StoreDeepResponse
	16, // 46: deltamem.DeltaMem.TurbogoSearch:output_type -> deltamem.TurboSearchResponse
	29, // 47: deltamem.DeltaMem.Validate:output_type -> deltamem.ValidateResponse
	31, // 48: deltamem.DeltaMem.QueryTemporal:output_type -> deltamem.TemporalResponse
	34, // 49: deltamem.DeltaMem.AmIConfident:output_type -> deltamem.ConfidenceResponse
	26, // [26:50] is the sub-list for method output_type
	2,  // [2:26] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_deltamem_proto_init() }
func file_deltamem_proto_init() {
	if File_deltamem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deltamem_proto_rawDesc), len(file_deltamem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_deltamem_proto_goTypes,
		DependencyIndexes: file_deltamem_proto_depIdxs,
		MessageInfos:      file_deltamem_proto_msgTypes,
	}.Build()
	File_deltamem_proto = out.File
	file_deltamem_proto_goTypes = nil
	file_deltamem_proto_depIdxs = nil
}
