// Code generated by protoc-gen-go. DO NOT EDIT.
package proto

type StoreRequest struct {
	Owner   string `json:"owner"`
	Key     string `json:"key"`
	Content string `json:"content"`
}
type StoreResponse struct {
	Ok        bool    `json:"ok"`
	StateNorm float32 `json:"state_norm"`
}
type RecallRequest struct {
	Owner string `json:"owner"`
	Query string `json:"query"`
}
type RecallResponse struct {
	Correction []float32 `json:"correction"`
	Confidence float32   `json:"confidence"`
}
type HiddenStoreRequest struct {
	Owner       string    `json:"owner"`
	HiddenState []float32 `json:"hidden_state"`
}
type HiddenRecallRequest struct {
	Owner      string    `json:"owner"`
	QueryState []float32 `json:"query_state"`
}
type HiddenRecallResponse struct {
	DeltaQ     []float32 `json:"delta_q"`
	DeltaO     []float32 `json:"delta_o"`
	Confidence float32   `json:"confidence"`
}
type HealthResponse struct {
	OwnersActive int32   `json:"owners_active"`
	AvgStateNorm float32 `json:"avg_state_norm"`
	TotalStores  int64   `json:"total_stores"`
	TotalRecalls int64   `json:"total_recalls"`
	Uptime       string  `json:"uptime"`
}
type OwnerRequest struct {
	Owner string `json:"owner"`
}
type Empty struct{}
type IBNNForwardRequest struct {
	Owner string `json:"owner"`
	Text  string `json:"text"`
}
type IBNNForwardHiddenRequest struct {
	Owner       string    `json:"owner"`
	HiddenState []float32 `json:"hidden_state"`
}
type IBNNForwardResponse struct {
	Output []float32 `json:"output"`
	Dim    int32     `json:"dim"`
}
type TurboAddRequest struct {
	Owner  string    `json:"owner"`
	Id     string    `json:"id"`
	Vector []float32 `json:"vector"`
}
type TurboAddResponse struct {
	Ok bool `json:"ok"`
}
type TurboSearchRequest struct {
	Owner string    `json:"owner"`
	Query []float32 `json:"query"`
	K     int32     `json:"k"`
}
type TurboSearchResponse struct {
	Ids    []string  `json:"ids"`
	Scores []float32 `json:"scores"`
}
type GenerateRequest struct {
	Owner  string `json:"owner"`
	Prompt string `json:"prompt"`
}
type GenerateResponse struct {
	Response string `json:"response"`
}
