// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

type DeltaMemServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	StoreHidden(context.Context, *HiddenStoreRequest) (*StoreResponse, error)
	RecallHidden(context.Context, *HiddenRecallRequest) (*HiddenRecallResponse, error)
	Health(context.Context, *Empty) (*HealthResponse, error)
	ResetState(context.Context, *OwnerRequest) (*Empty, error)
	IBNNForward(context.Context, *IBNNForwardRequest) (*IBNNForwardResponse, error)
	IBNNForwardHidden(context.Context, *IBNNForwardHiddenRequest) (*IBNNForwardResponse, error)
	TurboAdd(context.Context, *TurboAddRequest) (*TurboAddResponse, error)
	TurboSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error)
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	Think(context.Context, *ThinkRequest) (*ThinkResponse, error)
	StartWander(context.Context, *OwnerRequest) (*Empty, error)
	StopWander(context.Context, *OwnerRequest) (*Empty, error)
	HarvestWander(context.Context, *OwnerRequest) (*HarvestResponse, error)
	AddAxiom(context.Context, *AxiomRequest) (*Empty, error)
	Adapt(context.Context, *AdaptRequest) (*AdaptResponse, error)
	Learn(context.Context, *LearnRequest) (*Empty, error)
	Forget(context.Context, *ForgetRequest) (*Empty, error)
}

type UnimplementedDeltaMemServer struct{}

func (UnimplementedDeltaMemServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) StoreHidden(context.Context, *HiddenStoreRequest) (*StoreResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) RecallHidden(context.Context, *HiddenRecallRequest) (*HiddenRecallResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) ResetState(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) IBNNForward(context.Context, *IBNNForwardRequest) (*IBNNForwardResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) IBNNForwardHidden(context.Context, *IBNNForwardHiddenRequest) (*IBNNForwardResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) TurboAdd(context.Context, *TurboAddRequest) (*TurboAddResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) TurboSearch(context.Context, *TurboSearchRequest) (*TurboSearchResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Think(context.Context, *ThinkRequest) (*ThinkResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) StartWander(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) StopWander(context.Context, *OwnerRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) HarvestWander(context.Context, *OwnerRequest) (*HarvestResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) AddAxiom(context.Context, *AxiomRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Adapt(context.Context, *AdaptRequest) (*AdaptResponse, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Learn(context.Context, *LearnRequest) (*Empty, error) {
	return nil, nil
}
func (UnimplementedDeltaMemServer) Forget(context.Context, *ForgetRequest) (*Empty, error) {
	return nil, nil
}

func RegisterDeltaMemServer(s *grpc.Server, srv DeltaMemServer) {
	s.RegisterService(&_DeltaMem_serviceDesc, srv)
}

var _DeltaMem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deltamem.DeltaMem",
	HandlerType: (*DeltaMemServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/deltamem.proto",
}
